### ISSUE TITLE
Allow shows with a year in the canonical title to be parsed

### ISSUE THREAD

**Issue by jpenney** [ghickman/tvrenamr#64]
As [documented](http://tvrenamr.readthedocs.org/en/latest/known-issues.html#years-in-show-names) `tvr` will create files like `Some Show (2525)`, but it's not able to parse the series title back out of such files.  Allowing `(` and `)` in `show_name` seems to fix this for me.

In `main.py`, change:

```
series = r"(?P<show_name>[\w\s.',_-]+)"
```

to:

```
series = r"(?P<show_name>[\w\s\(\).',_-]+)"
```

**Comment by ghickman** [comment]
@jpenney – thanks for reporting this, sorry for the slow turn around time.  This should be out later today (along with lots of other bits and bobs that have also fallen to the wayside along the way!)
