### ISSUE TITLE
symlink option in config

### ISSUE THREAD

**Issue by ata2001** [ghickman/tvrenamr#87]
I'm thinking about adding the symlink option to the config.
But I'm unsure, cause it would obligate changes in the current structure.

Now, self.symlink is an instance variable of the TvRenamr class, however it's only needed inside the rename method (TvRenamr.rename). If we would pass it to TvRenamr.rename as an argument instead, it would be easy to implement config support.

What do you think?

I've attached a diff file, it's just a concept, do not merge it, I didn't test it.

[symlink config patch](https://github.com/ghickman/tvrenamr/files/818048/symlink_config.txt)

**Comment by ghickman** [comment]
@ata2001 – That's exactly how I would expect it to be passed down from the config.  If you make a PR with your changes I'd be happy to merge it.

Thanks again for all your work on the symlink feature!

**Comment by ata2001** [comment]
Hi!

I tried to test this, then found out, the other boolean config options are neither functional (don't work I mean).

The problem is:
If the option is boolean, click returns either True or False (that's why we call it boolean), so that will override command line, even if False. We could solve it by setting default to None, while is_flag is still true, like:
`@click.option('-t', '--the', is_flag=True, default=None, help="Set the position of 'The' in a show's name to the end of the show name")`

**Comment by ata2001** [comment]
Created PR.

**Comment by ata2001** [comment]
Solved by https://github.com/ghickman/tvrenamr/pull/88.
