### ISSUE TITLE
Not able to locate config file

### ISSUE THREAD

**Issue by mayankgautam** [ghickman/tvrenamr#91]
I want to edit the config file to change the naming convention. But I'm not able to find it in default location mentioned in the help documentation. 

Please can you help.

**Comment by ata2001** [comment]
You have to create the file first.

>By default it looks for it in ~/.tvrenamr/config.yml

**Comment by mayankgautam** [comment]
Please can you tell me how to create one.

**Comment by ata2001** [comment]
With your text editor.

If you're on UNIX:

`eval $EDITOR ~/.tvrenamr/config.yml`

**Comment by mayankgautam** [comment]
And add the following to it:

defaults:
  format: '%n - %s%e - %t%x'
  organise: yes
  renamed: /Volumes/Media/TV/
  symlink: true
  the: true

Right?

**Comment by mayankgautam** [comment]
Thanks for the help. Got it now.
