### ISSUE TITLE
To use tvrenamr as library

### ISSUE THREAD

**Issue by mayankgautam** [ghickman/tvrenamr#92]
Please can I get some pointers on how to use tvrenamr as library inside my program.

**Comment by ata2001** [comment]
We have no official documentation, however I did write a Kodi frontend for tvrenamr once. I've managed it by removing the click part from `tvrenamr/cli/core.py`, and calling `rename` from my script.

I know, it's not the best way to do it, but you can check out my source: [ata2001/script.customregex](https://github.com/ata2001/script.customregex)

And the modifications made to make it work without click: https://github.com/ata2001/tvrenamr/tree/kodi

**Comment by mayankgautam** [comment]
Really thanks man!!! Will check it out!!

**Comment by ata2001** [comment]
It's still just a hack, I think tvrenamr could provide more support or documentation for using it as a library.
