### ISSUE TITLE
copy instead of move?

### ISSUE THREAD

**Issue by shashi007** [ghickman/tvrenamr#93]
Is there by chance an option to copy series instead of moving it?

**Comment by ghickman** [comment]
@shashi007 – I'm afraid there isn't currently.  However if you'd like to contribute a pull request I'd gladly merge that functionality in :)

**Comment by ata2001** [comment]
@ghickman I may look into it tomorrow.

**Comment by ata2001** [comment]
@ghickman Would it be okay, if I implemented it the same way as symlinks?

**Comment by ata2001** [comment]
Created PR: #94.

**Comment by shashi007** [comment]
Thanks @ata2001
